#
#Jekyll Settings
#
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: kramdown
kramdown:
  input: GFM
  
highlighter: rouge

google_analytics: UA-30555770-1
title: Zein Sleiman

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: zein sleiman

description: Stylish Jekyll Theme
author:
  name: Zein Sleiman
  email: zein.hajjsleiman@gmail.com
  github: zeinsleiman
  linkedin: zeinhajjsleiman
  keybase: zeinsleiman
  bio: Software Engineer
  image: "/assets/images/zein.png"

permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-paginate
  - jekyll-seo-tag

collections:
  books:
